# Multiple Linear Regression-pipelines

## Importing the libraries

In [80]:
# Para guardar cambios en el script:  Ctrl + S

import numpy as np
#import matplotlib.pyplot as plt    
import pandas as pd

In [81]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle

## Importing the dataset

In [82]:
path_base = 'C:/MIDAGRI/CURSOS/DESPLIEGUE_ML/Tarea'
datos= pd.read_csv(f'{path_base}/data_modelo.csv', sep = ',')
datos.head(5)

,edad,edad2,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio,ingreso
0,43,1849,1,6,6,3,335,8423,4,22143.970703
1,46,2116,1,5,6,3,523,5610,4,13770.999023
2,44,1936,1,1,5,4,983,4100,4,10646.743164
3,71,5041,1,2,3,2,861,4330,4,4873.351074
4,36,1296,1,1,3,4,885,4923,4,10905.659180

In [83]:
datos.describe()

,edad,edad2,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio,ingreso
count,56234.000000,56234.000000,56234.000000,56234.000000,56234.000000,56234.00000,56234.000000,56234.000000,56234.000000,56234.000000
mean,43.418181,2136.725220,1.414998,3.002774,5.816446,2.71327,658.641800,4002.492407,4.821105,11766.008459
std,15.861628,1486.518838,0.492726,1.988468,2.426965,0.99497,235.177087,3218.861208,2.404406,11070.184460
min,14.000000,196.000000,1.000000,1.000000,1.000000,1.00000,11.000000,111.000000,1.000000,57.593796
25%,31.000000,961.000000,1.000000,1.000000,4.000000,2.00000,523.000000,150.000000,2.000000,5049.784058
50%,43.000000,1849.000000,1.000000,2.000000,6.000000,2.00000,615.000000,4721.000000,5.000000,8311.385254
75%,55.000000,3025.000000,2.000000,5.000000,8.000000,3.00000,885.000000,5610.000000,7.000000,14769.726807
max,98.000000,9604.000000,2.000000,6.000000,12.000000,6.00000,987.000000,9900.000000,8.000000,359772.843750

Data X e Y

In [84]:
# Separate features and target variable
X = datos[['edad', 'sexo', 'estado_civil','nivel_educativo', 'horas_trabajadas','categoria_ocupacional','actividad_empresa','dominio']]
y = datos["ingreso"]

Data Train y test

In [85]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# pipeline

In [86]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
# Assuming 'X' is your DataFrame, for example:
# import pandas as pd
# data = {'numeric_feat': [1, 2, 3], 'categorical_feat': ['A', 'B', 'A']}
# X = pd.DataFrame(data)

# Define numeric and categorical columns
numeric_cols = X.select_dtypes(include=np.number).columns.tolist()
categorical_cols = X.select_dtypes('object').columns.tolist()

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('numeric', StandardScaler(), numeric_cols),
        # --- FIX IS ON THIS LINE ---
        ('categorical', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), categorical_cols)
    ])

# Create a pipeline with preprocessing and the linear regression model
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

print("Pipeline created successfully!")

Pipeline created successfully!

# Fit

In [87]:
# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                                  ['edad', 'sexo',
                                                   'estado_civil',
                                                   'nivel_educativo',
                                                   'horas_trabajadas',
                                                   'categoria_ocupacional',
                                                   'actividad_empresa',
                                                   'dominio']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [])])),
                ('regressor', LinearRegression())])

In [88]:
# Predict using the pipeline
y_pred = pipeline.predict(X_test)
y_pred

array([15793.19188674, 10525.23167644, 18733.1765524 , ...,
        7741.24867996, 14548.20357026, 31903.46774372])

In [89]:
# Calculate RMSE
from sklearn.metrics import mean_squared_error  # Add this import
rmse = mean_squared_error(y_test, y_pred)**0.5
print(f"Root Mean Squared Error: {rmse}")

Root Mean Squared Error: 7458.324427031138

# Detalles del Modelo

In [90]:
import os, sys

In [91]:
#Llamamos al modelo

In [92]:
from joblib import dump
dump(pipeline, 'C:/MIDAGRI/CURSOS/DESPLIEGUE_ML/Tarea/Modelopipeline.joblib')

['C:/MIDAGRI/CURSOS/DESPLIEGUE_ML/Tarea/Modelopipeline.joblib']

In [93]:
from joblib import load
# regressor = LinearRegression()
regressor = load('C:/MIDAGRI/CURSOS/DESPLIEGUE_ML/Tarea/Modelopipeline.joblib') #Cargamos el modelo

### Nueva data

In [94]:
X = pd.DataFrame(columns=[ 'edad', 'sexo', 'estado_civil','nivel_educativo' ,'horas_trabajadas','categoria_ocupacional','actividad_empresa','dominio'
                                    ])

In [95]:
# Edad = 35
# Hombre (p207=1)
# Casado (p209=2)
# Universitaria completa (p301a=10)
# 48 horas (p507=48)
# Empleado (p505=3)
# Empresa de 11 a 50 trabajadores (p506r4=3)
# Lima Metropolitana (dominio=8)

In [114]:
obs =pd.DataFrame([ [ 42, 1, 2,4,48,3,3,8 ] ],columns=X.columns)
obs

,edad,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio
0,42,1,2,4,48,3,3,8

#### LLamamos el pickle de la transformación

In [97]:
#Cargamos el pickle de recodificación de categoricas
#with open('C:/Users/Orlando A/STREAMLIT-OAZ/Regresion_estand_cualit_app/encoderpipeline.pickle','rb') as f:
#    encoder = pickle.load(f)

In [98]:
# regressor contiene todas las transformaciones del pipeline: estandarizacion y dummy
y_pred=regressor.predict(obs)
y_pred   #167921.0656955

array([149287.55225816])

DATOS PARA DESPLIEGUE

In [99]:
datos.head(3) #datos es la base original

,edad,edad2,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio,ingreso
0,43,1849,1,6,6,3,335,8423,4,22143.970703
1,46,2116,1,5,6,3,523,5610,4,13770.999023
2,44,1936,1,1,5,4,983,4100,4,10646.743164

In [100]:
XX = datos[['edad', 'sexo', 'estado_civil', 'nivel_educativo','horas_trabajadas','categoria_ocupacional','actividad_empresa','dominio']]
yy = datos["ingreso"]

In [101]:
from sklearn.model_selection import train_test_split
XX_train, XX_test, yy_train, yy_test = train_test_split(XX, yy, test_size = 0.2, random_state = 0)

In [102]:
XX_test

,edad,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio
18650,63,2,5,8,3,522,5629,5
37511,42,1,2,5,2,615,150,5
50701,33,1,1,8,4,885,2396,5
21357,40,2,5,4,3,522,5610,1
14245,40,2,2,3,2,572,4721,5
...,...,...,...,...,...,...,...,...
53404,43,1,2,3,4,983,4100,7
49999,70,1,2,3,2,615,150,7
37908,50,1,2,3,2,615,150,7
21915,25,2,6,8,3,413,8620,1
43620,56,1,6,11,3,247,8530,7

In [103]:
#Uniendo
union = pd.concat([ XX_test, yy_test], axis=1)
union

,edad,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio,ingreso
18650,63,2,5,8,3,522,5629,5,14039.126953
37511,42,1,2,5,2,615,150,5,5766.923340
50701,33,1,1,8,4,885,2396,5,19948.009766
21357,40,2,5,4,3,522,5610,1,7739.202148
14245,40,2,2,3,2,572,4721,5,5473.573730
...,...,...,...,...,...,...,...,...,...
53404,43,1,2,3,4,983,4100,7,11967.715820
49999,70,1,2,3,2,615,150,7,3701.595947
37908,50,1,2,3,2,615,150,7,5580.854004
21915,25,2,6,8,3,413,8620,1,8178.632324
43620,56,1,6,11,3,247,8530,7,19053.392578

Con los datos X_test ya estandarizados y con dummy calculamos

# COMPROBANDO para 1 caso

In [104]:
X = pd.DataFrame(columns=[ 'edad','sexo','estado_civil','nivel_educativo','horas_trabajadas','categoria_ocupacional','actividad_empresa','dominio'])
obs =pd.DataFrame([ [	42,	1,	2,1,	24,	522,	150,	2  ] ],columns=X.columns)
obs

,edad,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio
0,42,1,2,1,24,522,150,2

In [105]:
# regressor contiene el pipeline.
y_pred = regressor.predict(obs)
y_pred  #Coincide con el anterior

array([66207.45440152])

PARA TODO EL DATAFRAME

In [106]:
#Uniendo
union = pd.concat([ XX_test, yy_test], axis=1)
union.head(3)

,edad,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio,ingreso
18650,63,2,5,8,3,522,5629,5,14039.126953
37511,42,1,2,5,2,615,150,5,5766.923340
50701,33,1,1,8,4,885,2396,5,19948.009766

In [107]:
unionf=union

In [108]:
obs =unionf
obs

,edad,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio,ingreso
18650,63,2,5,8,3,522,5629,5,14039.126953
37511,42,1,2,5,2,615,150,5,5766.923340
50701,33,1,1,8,4,885,2396,5,19948.009766
21357,40,2,5,4,3,522,5610,1,7739.202148
14245,40,2,2,3,2,572,4721,5,5473.573730
...,...,...,...,...,...,...,...,...,...
53404,43,1,2,3,4,983,4100,7,11967.715820
49999,70,1,2,3,2,615,150,7,3701.595947
37908,50,1,2,3,2,615,150,7,5580.854004
21915,25,2,6,8,3,413,8620,1,8178.632324
43620,56,1,6,11,3,247,8530,7,19053.392578

In [109]:
# regressor contiene los pasos del pipeline
y_pred = regressor.predict(obs)
y_pred  #Coincide con el anterior

array([15793.19188674, 10525.23167644, 18733.1765524 , ...,
        7741.24867996, 14548.20357026, 31903.46774372])

In [110]:
Profit_predict = pd.DataFrame( y_pred, columns=['Profit_predict'])
Profit_predict

       Profit_predict
0        15793.191887
1        10525.231676
2        18733.176552
3         5789.734774
4         3262.329459
...               ...
11242     8728.631508
11243     8902.793792
11244     7741.248680
11245    14548.203570
11246    31903.467744

[11247 rows x 1 columns]

In [111]:
union = pd.concat([ XX_test, yy_test], axis=1)
union.head(3)

,edad,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio,ingreso
18650,63,2,5,8,3,522,5629,5,14039.126953
37511,42,1,2,5,2,615,150,5,5766.923340
50701,33,1,1,8,4,885,2396,5,19948.009766

In [112]:
Profit_predict_f = Profit_predict.reset_index(drop=True)
union_f = union.reset_index(drop=True)

unionfff= pd.concat([ union_f,Profit_predict_f], axis=1)
unionfff

,edad,sexo,estado_civil,nivel_educativo,horas_trabajadas,categoria_ocupacional,actividad_empresa,dominio,ingreso,Profit_predict
0,63,2,5,8,3,522,5629,5,14039.126953,15793.191887
1,42,1,2,5,2,615,150,5,5766.923340,10525.231676
2,33,1,1,8,4,885,2396,5,19948.009766,18733.176552
3,40,2,5,4,3,522,5610,1,7739.202148,5789.734774
4,40,2,2,3,2,572,4721,5,5473.573730,3262.329459
...,...,...,...,...,...,...,...,...,...,...
11242,43,1,2,3,4,983,4100,7,11967.715820,8728.631508
11243,70,1,2,3,2,615,150,7,3701.595947,8902.793792
11244,50,1,2,3,2,615,150,7,5580.854004,7741.248680
11245,25,2,6,8,3,413,8620,1,8178.632324,14548.203570
11246,56,1,6,11,3,247,8530,7,19053.392578,31903.467744